apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: viewer
  namespace: netology-test
rules:
  - apiGroups: ["", "extensions", "apps"]
    resources: ["pods","pods/log"]
    verbs: ["get", "list", "watch"]
