apiVersion: v1
kind: Service
metadata:
  name: myservice-1
spec:
  selector:
    app: nginx
  ports:
  - name: nginx
    protocol: TCP
    port: 80
    nodePort: 30080
  - name: multitool
    protocol: TCP
    port: 8080
    nodePort: 31080 
  type: NodePort
