apiVersion: v1
kind: Pod
metadata:
  name: netology-web
  labels:
     app: nginx
spec:
  containers:
  - name: multitool
    image: wbitt/network-multitool:latest
    ports:
    - containerPort: 80

